export const MAX_UPLOAD_FILES = 9;

export const PROTECTED_DRAFT_CONVERSATION = "__protected_draft__";
export const HISTORY_LIST_PAGE_SIZE = 80;
export const HISTORY_LIST_MIN_LOADING_MS = 260;
export const HISTORY_DETAIL_INITIAL_MAX_MESSAGES = 360;
export const HISTORY_SWITCH_OVERLAY_MIN_MS = 260;
export const PROJECT_HISTORY_DELETE_PAGE_SIZE = 200;
export const SHARED_HISTORY_LIST_PAGE_SIZE = 200;
export const HISTORY_TITLE_POSITION_LOCK_MS = 1200;
export const SECONDS_TIMESTAMP_MAX = 10_000_000_000;
export const DRAFT_HISTORY_ADOPTION_WINDOW_MS = 30_000;
export const LIVE_STREAM_HISTORY_REFRESH_SUPPRESS_MS = 30_000;
export const PAGE_RESTORE_HISTORY_REFRESH_THROTTLE_MS = 900;
export const CHAT_RUNTIME_PREPARE_TIMEOUT_MS = 2_500;
export const CHAT_RUNTIME_FOREGROUND_PREPARE_TIMEOUT_MS = 1_500;
export const CHAT_RUNTIME_KEEP_WARM_INTERVAL_MS = 10_000;
export const CHAT_RUNTIME_STARTING_STATUS_DELAY_MS = 1_200;
export const CHAT_RUNTIME_READY_STATUS_TTL_MS = 20_000;
export const CHAT_RUNTIME_PREPARING_STATUS = "Preparing request...";
export const CHAT_RUNTIME_STARTING_STATUS = "Starting desktop runtime...";

export const DEFAULT_BROWSER_TITLE = "LiveAgent Gateway";
export const NEW_CONVERSATION_BROWSER_TITLE = "LiveAgent";
export const SHARED_HISTORY_BROWSER_TITLE = "分享会话";
export const SKILLS_HUB_BROWSER_TITLE = "Skills Hub";
export const MCP_HUB_BROWSER_TITLE = "MCP Hub";

export const MOBILE_SIDEBAR_MEDIA_QUERY = "(max-width: 820px)";
